
development:
  adapter: postgresql
  database: flycosette-dev

test:
  adapter: postgresql
  database: flycosette-test

production:
  adapter: postgresql
  encoding: unicode
  database: flycosette-pro